Updating documentation links
reduxframework/redux-framework-4 pull request #187
Opened 2021-01-19 23:28 UTC by mohammedeisa

This commit contains updates to the sample options page documentation links.

2021-01-20 01:08 UTC, KevinBatdorf requested changes
I only looked at a few of them but the pages don't exist. Is there a plan to add these pages before this is updated?

(The old pages don't seem to exist either)

2021-01-20 01:08 UTC, KevinBatdorf commented on .github/ISSUE_TEMPLATE/dev.md
> +If you have purchased a theme or plugin that utilizes Redux, please contact the author for support. If the author is unavailable for support or has discontinued support, please refer to this before p
https://devs.redux.io/core/support-defined gives a 404

2021-01-20 01:08 UTC, KevinBatdorf commented on .github/ISSUE_TEMPLATE/dev.md
> +Also, unless you provide a Support Hash, your request will also be rejected.  NO exceptions.  If you do not including this information and we close your ticket, please do not ask why. See See https:/
404

2021-01-20 01:08 UTC, KevinBatdorf commented on sample/barebones-config.php
> +	'desc'       => esc_html__( 'For full documentation on this field, visit: ', 'your-textdomain-here' ) . '<a href="https://devs.redux.io/core-fields/textarea.html" target="_blank">//docs.redux.io/cor
This one still says docs

2021-01-20 18:41 UTC, mohammedeisa commented
@KevinBatdorf I think you can merge this commit as is and I will fix the undefined and the docs.redux.io ones.
About the inexistent pages, I prefer to keep them until we create pages with the same usage.

2021-01-21 01:41 UTC, KevinBatdorf commented
Can you create the pages first? Or otherwise add redirects?

Also, I'm not familiar enough with the codebase to be merging.

2021-01-21 21:18 UTC, mohammedeisa commented
> Can you create the pages first? Or otherwise add redirects?
> 
> Also, I'm not familiar enough with the codebase to be merging.

Currently, creating new pages for documentation is not a priority.
The priority is to make the documentation links in the plugin work.

2021-01-22 01:44 UTC, KevinBatdorf commented on sample/barebones-config.php
> +	'desc'       => esc_html__( 'For full documentation on this field, visit: ', 'your-textdomain-here' ) . '<a href="https://devs.redux.io/core-fields/textarea.html" target="_blank">//docs.redux.io/cor
<img width="798" alt="Screen Shot 2021-01-22 at 8 42 57 AM" src="https://user-images.githubusercontent.com/1478421/105434322-ea8a2c00-5c8d-11eb-99d6-513446c18574.png">

2021-01-22 01:45 UTC, KevinBatdorf commented
> The priority is to make the documentation links in the plugin work.

In general we should never add anything broken to production code. Are all the URLs working now?

2021-01-27 01:11 UTC, mohammedeisa commented
@KevinBatdorf It seems that there is something wrong with my IDE.
I found many other docs.redux.io occurrences that replaced them.
I commented out the unexisting documentation links and added links to the old documentation website docsv3.redux.io for the links that don't exist in devs.redux.io temporary until we create the same pages in devs.redux.io

2021-02-15 19:32 UTC, merged